### PR TITLE
added more to the intro paragraph

### PR DESCRIPTION
**Pull request by mbennette85**
Just changing the inner intro text

### CODE REVIEW

**Comment by eorstrom** [comment]
Hey Michael. I would change "web developers" to "software developers". I feel like that would be more inclusive of our skills and knowledge that we gained from the program. Otherwise, it sounds pretty good!

**Comment by mbennette85** [comment]
Changed 'web' to 'software' in latest commit and push

**Comment by eorstrom** [comment]
👍

**Comment by mbennette85** [comment]
I'll keep this branch open until we get what we want.

**Comment by eorstrom** [comment]
Okay sounds good. I think it only needs a little tweaking. but we're definitely on the right track. Thanks again Michael.

**Comment by mbennette85** [comment]
Added the technologies and revised the paragraph. Will merge upon approval

**Pull request merged**
